#!/bin/bash -e

cd "$(dirname "$0")"

usage() {
	echo \
"base_builder

Base Builder wraps up all the commands to create a box for Vagrant to use just from the defs.

Usage: $0 <definition>"

	exit 1
}

message() {
	echo "========================================================"
	echo "$@"
	echo "========================================================"
}

error() {
	message "ERROR: $@"
	exit 1
}

# default config
name=sl6-64-lyte

# parse cli options
while true; do
	# quit parsing if we're out of options
	[[ -z "$1" ]] && break

	case "$1" in
		--help)
			usage
			;;
		*)
			name="$1"
			;;
	esac

	# get next arg
	shift
done

message "Building"
veewee vbox build "$name" --force --nogui

message "Exporting"
sleep 5 # work around race condition where if you run export too quickly after build, it fails

veewee vbox export "$name" --force
